#!/bin/bash

set -ex

OUTPUT=$(kubectl run -it --restart=Never health-check --rm --image=busybox --quiet -- wget -O - -q http://hello-world/env.txt)
echo "Output: $OUTPUT"
[[ "$OUTPUT" = 'Hello world not from kind' ]]
