name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Minikube Setup
      uses: opsgang/ga-setup-minikube@v0.1.1
      with:
        minikube-version: 1.10.1
        k8s-version: 1.18.5
    - name: Minikube test
      run: |
        kubectl version
        kubectl get pods --all-namespaces
