name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: engineerd/setup-kind@v0.4.0
    - name: Kind Test
      run: |
        kubectl apply -k envs/kind
        kubectl wait pod -l app=hello-world --for=condition=Ready
        OUTPUT=$(kubectl run -it --restart=Never health-checkers --rm --image=busybox --quiet -- wget -O - -q http://hello-world/env.txt)
        echo "Output: $OUTPUT"
        [[ "$OUTPUT" = "Hello world from kind" ]]
